/**
 * @file cooling_system.c
 *
 * @brief This source file was generated by cantools version 43.0.0 Thu Oct  1 19:50:53 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "cooling_system.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int cooling_system_flow1_pack(
    uint8_t *dst_p,
    const struct cooling_system_flow1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rate_lpm_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rate_lpm_1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->total_volume_l_1, 24u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->total_volume_l_1, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->total_volume_l_1, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->total_volume_l_1, 0u, 0xffu);

    return (8);
}

int cooling_system_flow1_unpack(
    struct cooling_system_flow1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rate_lpm_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rate_lpm_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->total_volume_l_1 = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
    dst_p->total_volume_l_1 |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->total_volume_l_1 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->total_volume_l_1 |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);

    return (0);
}

int cooling_system_flow1_init(struct cooling_system_flow1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cooling_system_flow1_t));

    return 0;
}

uint16_t cooling_system_flow1_rate_lpm_1_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cooling_system_flow1_rate_lpm_1_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_flow1_rate_lpm_1_is_in_range(uint16_t value)
{
    return (value <= 30000u);
}

bool cooling_system_flow1_rate_lpm_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 300.0));
}

uint32_t cooling_system_flow1_total_volume_l_1_encode(double value)
{
    return (uint32_t)(value / 0.001);
}

double cooling_system_flow1_total_volume_l_1_decode(uint32_t value)
{
    return ((double)value * 0.001);
}

bool cooling_system_flow1_total_volume_l_1_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cooling_system_flow1_total_volume_l_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967.295));
}

int cooling_system_flow2_pack(
    uint8_t *dst_p,
    const struct cooling_system_flow2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rate_lpm_2, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rate_lpm_2, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->total_volume_l_2, 24u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->total_volume_l_2, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->total_volume_l_2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->total_volume_l_2, 0u, 0xffu);

    return (8);
}

int cooling_system_flow2_unpack(
    struct cooling_system_flow2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rate_lpm_2 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rate_lpm_2 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->total_volume_l_2 = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
    dst_p->total_volume_l_2 |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->total_volume_l_2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->total_volume_l_2 |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);

    return (0);
}

int cooling_system_flow2_init(struct cooling_system_flow2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cooling_system_flow2_t));

    return 0;
}

uint16_t cooling_system_flow2_rate_lpm_2_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cooling_system_flow2_rate_lpm_2_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_flow2_rate_lpm_2_is_in_range(uint16_t value)
{
    return (value <= 30000u);
}

bool cooling_system_flow2_rate_lpm_2_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 300.0));
}

uint32_t cooling_system_flow2_total_volume_l_2_encode(double value)
{
    return (uint32_t)(value / 0.001);
}

double cooling_system_flow2_total_volume_l_2_decode(uint32_t value)
{
    return ((double)value * 0.001);
}

bool cooling_system_flow2_total_volume_l_2_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cooling_system_flow2_total_volume_l_2_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967.295));
}

int cooling_system_temp_pack(
    uint8_t *dst_p,
    const struct cooling_system_temp_t *src_p,
    size_t size)
{
    uint16_t temp_c_1;
    uint16_t temp_c_2;
    uint16_t temp_c_3;
    uint16_t temp_c_4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    temp_c_1 = (uint16_t)src_p->temp_c_1;
    dst_p[0] |= pack_right_shift_u16(temp_c_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(temp_c_1, 0u, 0xffu);
    temp_c_2 = (uint16_t)src_p->temp_c_2;
    dst_p[2] |= pack_right_shift_u16(temp_c_2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(temp_c_2, 0u, 0xffu);
    temp_c_3 = (uint16_t)src_p->temp_c_3;
    dst_p[4] |= pack_right_shift_u16(temp_c_3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(temp_c_3, 0u, 0xffu);
    temp_c_4 = (uint16_t)src_p->temp_c_4;
    dst_p[6] |= pack_right_shift_u16(temp_c_4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(temp_c_4, 0u, 0xffu);

    return (8);
}

int cooling_system_temp_unpack(
    struct cooling_system_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t temp_c_1;
    uint16_t temp_c_2;
    uint16_t temp_c_3;
    uint16_t temp_c_4;

    if (size < 8u) {
        return (-EINVAL);
    }

    temp_c_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    temp_c_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->temp_c_1 = (int16_t)temp_c_1;
    temp_c_2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    temp_c_2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->temp_c_2 = (int16_t)temp_c_2;
    temp_c_3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    temp_c_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->temp_c_3 = (int16_t)temp_c_3;
    temp_c_4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    temp_c_4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->temp_c_4 = (int16_t)temp_c_4;

    return (0);
}

int cooling_system_temp_init(struct cooling_system_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cooling_system_temp_t));

    return 0;
}

int16_t cooling_system_temp_temp_c_1_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double cooling_system_temp_temp_c_1_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_temp_temp_c_1_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 20000));
}

bool cooling_system_temp_temp_c_1_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 200.0));
}

int16_t cooling_system_temp_temp_c_2_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double cooling_system_temp_temp_c_2_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_temp_temp_c_2_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 20000));
}

bool cooling_system_temp_temp_c_2_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 200.0));
}

int16_t cooling_system_temp_temp_c_3_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double cooling_system_temp_temp_c_3_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_temp_temp_c_3_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 20000));
}

bool cooling_system_temp_temp_c_3_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 200.0));
}

int16_t cooling_system_temp_temp_c_4_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double cooling_system_temp_temp_c_4_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool cooling_system_temp_temp_c_4_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 20000));
}

bool cooling_system_temp_temp_c_4_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 200.0));
}
