/**
 * @file cooling_system.h
 *
 * @brief This header file was generated by cantools version 43.0.0 Tue Aug 25 18:19:50 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef COOLING_SYSTEM_H
#define COOLING_SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define COOLING_SYSTEM_FLOW1_FRAME_ID (0x100u)
#define COOLING_SYSTEM_FLOW2_FRAME_ID (0x101u)

/* Frame lengths in bytes. */
#define COOLING_SYSTEM_FLOW1_LENGTH (8u)
#define COOLING_SYSTEM_FLOW2_LENGTH (8u)

/* Extended or standard frame types. */
#define COOLING_SYSTEM_FLOW1_IS_EXTENDED (0)
#define COOLING_SYSTEM_FLOW2_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define COOLING_SYSTEM_FLOW1_CYCLE_TIME_MS (100u)
#define COOLING_SYSTEM_FLOW2_CYCLE_TIME_MS (100u)

/* Signal choices. */


/* Frame Names. */
#define COOLING_SYSTEM_FLOW1_NAME "FLOW1"
#define COOLING_SYSTEM_FLOW2_NAME "FLOW2"

/* Signal Names. */
#define COOLING_SYSTEM_FLOW1_RATE_LPM_1_NAME "rate_lpm_1"
#define COOLING_SYSTEM_FLOW1_TOTAL_VOLUME_L_1_NAME "total_volume_l_1"
#define COOLING_SYSTEM_FLOW2_RATE_LPM_2_NAME "rate_lpm_2"
#define COOLING_SYSTEM_FLOW2_TOTAL_VOLUME_L_2_NAME "total_volume_l_2"

/**
 * Signals in message FLOW1.
 *
 * Flow channel 1: rate + cumulative total volume.
 *
 * All signal values are as on the CAN bus.
 */
struct cooling_system_flow1_t {
    /**
     * Range: 0..30000 (0..300 L/min)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t rate_lpm_1;

    /**
     * Range: 0..4294967295 (0..4294967.295 L)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t total_volume_l_1;
};

/**
 * Signals in message FLOW2.
 *
 * Flow channel 2: rate + cumulative total volume.
 *
 * All signal values are as on the CAN bus.
 */
struct cooling_system_flow2_t {
    /**
     * Range: 0..30000 (0..300 L/min)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t rate_lpm_2;

    /**
     * Range: 0..4294967295 (0..4294967.295 L)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t total_volume_l_2;
};

/**
 * Pack message FLOW1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cooling_system_flow1_pack(
    uint8_t *dst_p,
    const struct cooling_system_flow1_t *src_p,
    size_t size);

/**
 * Unpack message FLOW1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cooling_system_flow1_unpack(
    struct cooling_system_flow1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FLOW1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cooling_system_flow1_init(struct cooling_system_flow1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t cooling_system_flow1_rate_lpm_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cooling_system_flow1_rate_lpm_1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow1_rate_lpm_1_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow1_rate_lpm_1_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cooling_system_flow1_total_volume_l_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cooling_system_flow1_total_volume_l_1_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow1_total_volume_l_1_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow1_total_volume_l_1_is_in_phys_range(double value);

/**
 * Pack message FLOW2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cooling_system_flow2_pack(
    uint8_t *dst_p,
    const struct cooling_system_flow2_t *src_p,
    size_t size);

/**
 * Unpack message FLOW2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cooling_system_flow2_unpack(
    struct cooling_system_flow2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FLOW2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cooling_system_flow2_init(struct cooling_system_flow2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t cooling_system_flow2_rate_lpm_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cooling_system_flow2_rate_lpm_2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow2_rate_lpm_2_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow2_rate_lpm_2_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cooling_system_flow2_total_volume_l_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cooling_system_flow2_total_volume_l_2_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow2_total_volume_l_2_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cooling_system_flow2_total_volume_l_2_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
